// Code generated by goctl. DO NOT EDIT.
package types

type RecoveryInfo struct {
	ServerVersion string `json:"server_version"`
	ServerID      int    `json:"server_id"`
	BinlogDir     string `json:"binlog_dir"`
}

type FakeMasterInfo struct {
	User     string `json:"user"`
	Password string `json:"password"`
	Port     int    `json:"port"`
}

type RecoveryByTimeRequest struct {
	Info             RecoveryInfo `json:"info"`
	RecoverTimestamp int64        `json:"recover_timestamp"`
}

type RecoveryByTimeResponse struct {
	Code           int32           `json:"code"`
	Message        string          `json:"message"`
	FakeMasterInfo *FakeMasterInfo `json:"fake_master_info"`
}

type RecoveryByGTIDRequest struct {
}

type RecoveryByGTIDResponse struct {
}
